services:
  db:
    image: "postgres:17"
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "pg_data:/var/lib/postgres/data"
      - "./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql"
      - "./files:/files"

    ports:
      - "5433:5432"

volumes:
  pg_data: {}
